# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='novo_preco',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Novo Preço'),
        ),
    ]
