# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import guiaofertas.apps.core.models.abstratas.Uf


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('ramal', models.IntegerField(blank=True, null=True, verbose_name='Ramal')),
                ('celular', models.CharField(blank=True, max_length=16, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('privado', models.BooleanField(verbose_name='Oculto')),
            ],
            options={
                'verbose_name': 'Contato',
                'ordering': ['-created'],
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=14, verbose_name='CNPJ')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identificador')),
                ('descricao', models.CharField(blank=True, max_length=250, verbose_name='Descrição')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Logomarca')),
            ],
            options={
                'verbose_name': 'Empresa',
                'ordering': ['-created'],
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('logradouro', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=30, verbose_name='Número')),
                ('bairro', models.CharField(max_length=150, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=150, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PR', 'Paraná'), ('PB', 'Paraíba'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default=guiaofertas.apps.core.models.abstratas.Uf.Uf('Rio de Janeiro'), max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=150, verbose_name='Complemento')),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Latitude')),
                ('privado', models.BooleanField(verbose_name='Oculto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='empresas.Empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Endereço',
                'ordering': ['-created'],
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AddField(
            model_name='contato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='empresas.Empresa', verbose_name='Empresa'),
        ),
    ]
